timeout-minutes job level

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -1,35 +1,35 @@
 name: Status check functions
 on: [push]
 jobs:
-    job1:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Step 1
-              run: sleep 90
-              timeout-minutes: 1
-            - name: Step 2
-              id: step2
-              run: exit 1
-              continue-on-error: true
-            - name: run on step2 failure
-              if: failure() && steps.step2.conclusion == 'failure'
-              run: echo "Job failed"
-            - name: run on failure
-              if: failure()
-              run: echo "Job failed"
-            - name: run on success
-              if: success()
-              run: echo "Job succeeded"
-            - name: run on always
-              if: always()
-              run: echo "Job completed"
-            - name: run on cancelled
-              if: cancelled()
-              run: echo "Job was cancelled"
-    job2:
-        runs-on: ubuntu-latest
-        needs: job1
+  job1:
+    timeout-minutes: 1
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step 1
+        run: sleep 90
+      - name: Step 2
+        id: step2
+        run: exit 1
+        continue-on-error: true
+      - name: run on step2 failure
+        if: failure() && steps.step2.conclusion == 'failure'
+        run: echo "Job failed"
+      - name: run on failure
         if: failure()
-        steps:
-            - name: run if job 1 failure
-              run: echo "Job 1 failed, so job 2 is running"
+        run: echo "Job failed"
+      - name: run on success
+        if: success()
+        run: echo "Job succeeded"
+      - name: run on always
+        if: always()
+        run: echo "Job completed"
+      - name: run on cancelled
+        if: cancelled()
+        run: echo "Job was cancelled"
+  job2:
+    runs-on: ubuntu-latest
+    needs: job1
+    if: failure()
+    steps:
+      - name: run if job 1 failure
+        run: echo "Job 1 failed, so job 2 is running"
